server:
  port: 9002
spring:
  application:
    name: order_service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.201.65.162:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Hahug66
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5 #发送心跳的间隔
    lease-expiration-duration-in-seconds: 10 #续约到期的时间
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
